import java.awt.Color;

import javax.swing.BorderFactory;

public class Function_Light {
Main gui;
public Function_Light(Main gui) {
	this.gui = gui;
}
public void createMode(String color) {
	switch(color) {
	//case for darkMode
	case"dark" :
		gui.window.getContentPane().setBackground( new Color(50,50,50));
		gui.textarea.setBackground( new Color(50,50,50));
		gui.textarea.setForeground(Color.WHITE);
		gui.scrollbar.getVerticalScrollBar().setBackground(Color.BLACK);
		gui.scrollbar.getHorizontalScrollBar().setBackground(Color.BLACK);
		gui.menubar.setBackground(Color.BLACK);
		gui.menubar.setForeground(Color.WHITE);
		gui.menubar.setBorder(BorderFactory.createLineBorder(Color.BLACK,2));
		gui.menuFile.setForeground(Color.WHITE);
		gui.menuFile.getPopupMenu().setBorder(BorderFactory.createLineBorder(Color.BLACK,1));
		gui.menuEdit.setForeground(Color.WHITE);
		gui.menuEdit.getPopupMenu().setBorder(BorderFactory.createLineBorder(Color.BLACK,1));
		gui.menuFormat.setForeground(Color.WHITE);
		gui.menuFormat.getPopupMenu().setBorder(BorderFactory.createLineBorder(Color.BLACK,1));
		gui.iPrint.setForeground(Color.WHITE);
		gui.menuMode.setForeground(Color.WHITE);
		gui.menuMode.getPopupMenu().setBorder(BorderFactory.createLineBorder(Color.BLACK,1));
		gui.iNew.setBackground(Color.BLACK);
		gui.iNew.setForeground(Color.WHITE);
		gui.iOpen.setBackground(Color.BLACK);
		gui.iOpen.setForeground(Color.WHITE);
		gui.iPrint.setBackground(Color.BLACK);
		gui.iPrint.setForeground(Color.WHITE);
		gui.iSave.setBackground(Color.BLACK);
		gui.iSave.setForeground(Color.WHITE);
		gui.iSaveAs.setBackground(Color.BLACK);
		gui.iSaveAs.setForeground(Color.WHITE);
		gui.iExit.setBackground(Color.BLACK);
		gui.iExit.setForeground(Color.WHITE);
		gui.iWordwrap.setBackground(Color.BLACK);
		gui.iWordwrap.setForeground(Color.WHITE);
		gui.menuFont.setBackground(Color.BLACK);
		gui.menuFont.getPopupMenu().setBorder(BorderFactory.createLineBorder(Color.BLACK,1));
		gui.menuFont.setForeground(Color.WHITE);
		gui.menuFontSize.setBackground(Color.BLACK);
		gui.menuFontSize.setForeground(Color.WHITE);
		gui.menuFontSize.getPopupMenu().setBorder(BorderFactory.createLineBorder(Color.BLACK,1));
		gui.iArial.setBackground(Color.BLACK);
		gui.iArial.setForeground(Color.WHITE);
		gui.iAgency.setForeground(Color.WHITE);
		gui.iAgency.setBackground(Color.BLACK);
		gui.iCalibri.setForeground(Color.WHITE);
		gui.iCalibri.setBackground(Color.BLACK);
		gui.iCambria.setForeground(Color.WHITE);
		gui.iCambria.setBackground(Color.BLACK);
		gui.iTimesRoman.setForeground(Color.WHITE);
		gui.iTimesRoman.setBackground(Color.BLACK);
		gui.iSitkaSmall.setForeground(Color.WHITE);
		gui.iSitkaSmall.setBackground(Color.BLACK);
		gui.iFontSize12.setForeground(Color.WHITE);
		gui.iFontSize12.setBackground(Color.BLACK);
		gui.iFontSize14.setForeground(Color.WHITE);
		gui.iFontSize14.setBackground(Color.BLACK);
		gui.iFontSize16.setForeground(Color.WHITE);
		gui.iFontSize16.setBackground(Color.BLACK);
		gui.iFontSize18.setForeground(Color.WHITE);
		gui.iFontSize18.setBackground(Color.BLACK);
		gui.iFontSize20.setForeground(Color.WHITE);
		gui.iFontSize20.setBackground(Color.BLACK);
		gui.iFontSize22.setForeground(Color.WHITE);
		gui.iFontSize22.setBackground(Color.BLACK);
		gui.iFontSize24.setForeground(Color.WHITE);
		gui.iFontSize24.setBackground(Color.BLACK);
		gui.iFontSize26.setForeground(Color.WHITE);
		gui.iFontSize26.setBackground(Color.BLACK);
		gui.iFontSize28.setForeground(Color.WHITE);
		gui.iFontSize28.setBackground(Color.BLACK);
		gui.iFontSize36.setForeground(Color.WHITE);
		gui.iFontSize36.setBackground(Color.BLACK);
		gui.iFontSize42.setForeground(Color.WHITE);
		gui.iFontSize42.setBackground(Color.BLACK);
		gui.iFontSize56.setForeground(Color.WHITE);
		gui.iFontSize56.setBackground(Color.BLACK);
		gui.iFontSize72.setForeground(Color.WHITE);
	    gui.iFontSize72.setBackground(Color.BLACK); 
	    gui.iundo.setForeground(Color.WHITE);
	    gui.iundo.setBackground(Color.BLACK);
	    gui.icut.setForeground(Color.WHITE);
	    gui.icut.setBackground(Color.BLACK);
	    gui.icopy.setForeground(Color.WHITE);
	    gui.icopy.setBackground(Color.BLACK);
	    gui.ipaste.setForeground(Color.WHITE);
	    gui.ipaste.setBackground(Color.BLACK);
	    gui.darkMode.setForeground(Color.WHITE);
	    gui.darkMode.setBackground(Color.BLACK);
	    gui.lightMode.setForeground(Color.WHITE);
	    gui.lightMode.setBackground(Color.BLACK);
		break;
	//case for light mode	
	case "light" :
		gui.window.getContentPane().setBackground(Color.WHITE);
		gui.textarea.setBackground(Color.WHITE);
		gui.textarea.setForeground(Color.BLACK);
		gui.scrollbar.getVerticalScrollBar().setBackground(new Color(197,197,197));
		gui.scrollbar.getHorizontalScrollBar().setBackground(new Color(197,197,197));
		gui.menubar.setBackground(new Color(197,197,197));
		gui.menubar.setForeground(Color.BLACK);
		gui.menubar.setBorder(BorderFactory.createLineBorder(new Color(197,197,197),1));
		gui.menuFile.setForeground(Color.BLACK);
		gui.menuFile.getPopupMenu().setBorder(BorderFactory.createLineBorder(new Color(197,197,197),1));
		gui.menuEdit.setForeground(Color.BLACK);
		gui.menuEdit.getPopupMenu().setBorder(BorderFactory.createLineBorder(new Color(197,197,197),1));
		gui.menuFormat.setForeground(Color.BLACK);
		gui.menuFormat.getPopupMenu().setBorder(BorderFactory.createLineBorder(new Color(197,197,197),1));
		gui.iPrint.setForeground(Color.BLACK);
		gui.menuMode.setForeground(Color.BLACK);
		gui.menuMode.getPopupMenu().setBorder(BorderFactory.createLineBorder(new Color(197,197,197),1));
		gui.iNew.setBackground(new Color(197,197,197));
		gui.iNew.setForeground(Color.BLACK);
		gui.iOpen.setBackground(new Color(197,197,197));
		gui.iOpen.setForeground(Color.BLACK);
		gui.iPrint.setBackground(new Color(197,197,197));
		gui.iPrint.setForeground(Color.BLACK);
		gui.iSave.setBackground(new Color(197,197,197));
		gui.iSave.setForeground(Color.BLACK);
		gui.iSaveAs.setBackground(new Color(197,197,197));
		gui.iSaveAs.setForeground(Color.BLACK);
		gui.iExit.setBackground(new Color(197,197,197));
		gui.iExit.setForeground(Color.BLACK);
		gui.iWordwrap.setBackground(new Color(197,197,197));
		gui.iWordwrap.setForeground(Color.BLACK);
		gui.menuFont.setBackground(new Color(197,197,197));
		gui.menuFont.getPopupMenu().setBorder(BorderFactory.createLineBorder(new Color(197,197,197),1));
		gui.menuFont.setForeground(Color.BLACK);
		gui.menuFontSize.setBackground(new Color(197,197,197));
		gui.menuFontSize.setForeground(Color.BLACK);
		gui.menuFontSize.getPopupMenu().setBorder(BorderFactory.createLineBorder(new Color(197,197,197),1));
		gui.iArial.setBackground(new Color(197,197,197));
		gui.iArial.setForeground(Color.BLACK);
		gui.iAgency.setForeground(Color.BLACK);
		gui.iAgency.setBackground(new Color(197,197,197));
		gui.iCalibri.setForeground(Color.BLACK);
		gui.iCalibri.setBackground(new Color(197,197,197));
		gui.iCambria.setForeground(Color.BLACK);
		gui.iCambria.setBackground(new Color(197,197,197));
		gui.iTimesRoman.setForeground(Color.BLACK);
		gui.iTimesRoman.setBackground(new Color(197,197,197));
		gui.iSitkaSmall.setForeground(Color.BLACK);
		gui.iSitkaSmall.setBackground(new Color(197,197,197));
		gui.iFontSize12.setForeground(Color.BLACK);
		gui.iFontSize12.setBackground(new Color(197,197,197));
		gui.iFontSize14.setForeground(Color.BLACK);
		gui.iFontSize14.setBackground(new Color(197,197,197));
		gui.iFontSize16.setForeground(Color.BLACK);
		gui.iFontSize16.setBackground(new Color(197,197,197));
		gui.iFontSize18.setForeground(Color.BLACK);
		gui.iFontSize18.setBackground(new Color(197,197,197));
		gui.iFontSize20.setForeground(Color.BLACK);
		gui.iFontSize20.setBackground(new Color(197,197,197));
		gui.iFontSize22.setForeground(Color.BLACK);
		gui.iFontSize22.setBackground(new Color(197,197,197));
		gui.iFontSize24.setForeground(Color.BLACK);
		gui.iFontSize24.setBackground(new Color(197,197,197));
		gui.iFontSize26.setForeground(Color.BLACK);
		gui.iFontSize26.setBackground(new Color(197,197,197));
		gui.iFontSize28.setForeground(Color.BLACK);
		gui.iFontSize28.setBackground(new Color(197,197,197));
		gui.iFontSize36.setForeground(Color.BLACK);
		gui.iFontSize36.setBackground(new Color(197,197,197));
		gui.iFontSize42.setForeground(Color.BLACK);
		gui.iFontSize42.setBackground(new Color(197,197,197));
		gui.iFontSize56.setForeground(Color.BLACK);
		gui.iFontSize56.setBackground(new Color(197,197,197));
		gui.iFontSize72.setForeground(Color.BLACK);
	    gui.iFontSize72.setBackground(new Color(197,197,197)); 
	    gui.iundo.setForeground(Color.BLACK);
	    gui.iundo.setBackground(new Color(197,197,197));
	    gui.icut.setForeground(Color.BLACK);
	    gui.icut.setBackground(new Color(197,197,197));
	    gui.icopy.setForeground(Color.BLACK);
	    gui.icopy.setBackground(new Color(197,197,197));
	    gui.ipaste.setForeground(Color.BLACK);
	    gui.ipaste.setBackground(new Color(197,197,197));
	    gui.darkMode.setForeground(Color.BLACK);
	    gui.darkMode.setBackground(new Color(197,197,197));
	    gui.lightMode.setForeground(Color.BLACK);
	    gui.lightMode.setBackground(new Color(197,197,197));
		break;
	}
}
}
